Repository Tamanna-S/javaScript-projects, pull requests merged in 2022-10, with the labels that each got.

#4 Added a JavaScript Card Game
  basic-projects/Blackjack Game/Images/table.jpg
  basic-projects/Blackjack Game/README.md
  basic-projects/Blackjack Game/index.html
  basic-projects/Blackjack Game/script.js
  basic-projects/Blackjack Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added the Project: Ayush-Kanduri-Five-Digit-Timer
  basic-projects/Ayush-Kanduri-Five-Digit-Timer/README.md
  basic-projects/Ayush-Kanduri-Five-Digit-Timer/index.html
  basic-projects/Ayush-Kanduri-Five-Digit-Timer/script.js
  basic-projects/Ayush-Kanduri-Five-Digit-Timer/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#2 Add rock-paper-scissors game
  intermediate-projects/virejdasani-rock-paper-scissors/README.md
  intermediate-projects/virejdasani-rock-paper-scissors/index.html
  intermediate-projects/virejdasani-rock-paper-scissors/main.js
  intermediate-projects/virejdasani-rock-paper-scissors/screenshot.png
Labels: hacktoberfest, hacktoberfest-accepted

#3 weather app
  advance-projects/Shraddha16092002-WeatherApp/README.md
  advance-projects/Shraddha16092002-WeatherApp/index.html
  advance-projects/Shraddha16092002-WeatherApp/script.js
  advance-projects/Shraddha16092002-WeatherApp/style.css
  advance-projects/Shraddha16092002-WeatherApp/title-icon.png
Labels: hacktoberfest, hacktoberfest-accepted

#1 basic javascript calculator
  basic-projects/arpitjha867-calculator/README.md
  basic-projects/arpitjha867-calculator/index.html
  basic-projects/arpitjha867-calculator/index.js
  basic-projects/arpitjha867-calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#9 Added pig-game in intermediate-projects
  intermediate-projects/hasnain666-pig-game/Images/dice-1.png
  intermediate-projects/hasnain666-pig-game/Images/dice-2.png
  intermediate-projects/hasnain666-pig-game/Images/dice-3.png
  intermediate-projects/hasnain666-pig-game/Images/dice-4.png
  intermediate-projects/hasnain666-pig-game/Images/dice-5.png
  intermediate-projects/hasnain666-pig-game/Images/dice-6.png
  intermediate-projects/hasnain666-pig-game/README.md
  intermediate-projects/hasnain666-pig-game/index.html
  intermediate-projects/hasnain666-pig-game/script.js
  intermediate-projects/hasnain666-pig-game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added My Project (BMI Calculator)
  basic-projects/imobasshir-bmicalculator/README.md
  basic-projects/imobasshir-bmicalculator/index.html
  basic-projects/imobasshir-bmicalculator/index.js
  basic-projects/imobasshir-bmicalculator/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#13 Created HangMan Game
  intermediate-projects/Anshumansengar-Hangman-Game/Hangman_anshuman.mp4
  intermediate-projects/Anshumansengar-Hangman-Game/README.md
  intermediate-projects/Anshumansengar-Hangman-Game/index.html
  intermediate-projects/Anshumansengar-Hangman-Game/script.js
  intermediate-projects/Anshumansengar-Hangman-Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added basic blogwebsite in intermediate-projects
  intermediate-projects/Harsh3341-BlogWebsite/README.md
  intermediate-projects/Harsh3341-BlogWebsite/css/about.css
  intermediate-projects/Harsh3341-BlogWebsite/css/compose.css
  intermediate-projects/Harsh3341-BlogWebsite/css/contact.css
  intermediate-projects/Harsh3341-BlogWebsite/css/home.css
  intermediate-projects/Harsh3341-BlogWebsite/css/navbar.css
  intermediate-projects/Harsh3341-BlogWebsite/pages/about.html
  intermediate-projects/Harsh3341-BlogWebsite/pages/compose.html
  intermediate-projects/Harsh3341-BlogWebsite/pages/contact.html
  intermediate-projects/Harsh3341-BlogWebsite/pages/home.html
  intermediate-projects/Harsh3341-BlogWebsite/script.js
  intermediate-projects/Harsh3341-BlogWebsite/script2.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added the Project: Ayush-Kanduri-Ping-Pong-Game
  .vscode/settings.json
  basic-projects/Ayush-Kanduri-Todo-List-App/Module.js
  basic-projects/Ayush-Kanduri-Todo-List-App/README.md
  basic-projects/Ayush-Kanduri-Todo-List-App/Script.js
  basic-projects/Ayush-Kanduri-Todo-List-App/Task.js
  basic-projects/Ayush-Kanduri-Todo-List-App/assets/images/banner.jpg
  basic-projects/Ayush-Kanduri-Todo-List-App/index.html
  basic-projects/Ayush-Kanduri-Todo-List-App/media-query.css
  basic-projects/Ayush-Kanduri-Todo-List-App/style.css
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/Ball.js
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/Paddle.js
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/README.md
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/index.html
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/script.js
  intermediate-projects/Ayush-Knaduri-Ping-Pong-Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 added animation in counter app
  basic-projects/counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#16 Pomodoro Timer App with JavaScript
  README.md
  basic-projects/Bagusin-Pomodoro-Timer/README.md
  basic-projects/Bagusin-Pomodoro-Timer/backtowork.mp3
  basic-projects/Bagusin-Pomodoro-Timer/break.mp3
  basic-projects/Bagusin-Pomodoro-Timer/button-sound.mp3
  basic-projects/Bagusin-Pomodoro-Timer/index.html
  basic-projects/Bagusin-Pomodoro-Timer/main.js
  basic-projects/Bagusin-Pomodoro-Timer/package-lock.json
  basic-projects/Bagusin-Pomodoro-Timer/package.json
  basic-projects/Bagusin-Pomodoro-Timer/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added the Project: Ayush-Kanduri-Todo-List-App-Using-API
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/Module.js
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/README.md
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/Script.js
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/bin.svg
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/index.html
  advance-projects/Ayush-Kanduri-Todo-List-App-Using-API/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#23 Typing Game
  basic-projects/LOKESH-PRASAD-TYPING-GAME/index.html
  basic-projects/LOKESH-PRASAD-TYPING-GAME/readme.md
  basic-projects/LOKESH-PRASAD-TYPING-GAME/script.js
  basic-projects/LOKESH-PRASAD-TYPING-GAME/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#22 adding basic-project simple-calculator
  basic-projects/theDreamer911-simple-calculator/README.md
  basic-projects/theDreamer911-simple-calculator/index.html
  basic-projects/theDreamer911-simple-calculator/index.js
  basic-projects/theDreamer911-simple-calculator/simple-calculator.gif
  basic-projects/theDreamer911-simple-calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 add my project
  intermediate-projects/DPGCode_Tic-tac-toe/index.html
  intermediate-projects/DPGCode_Tic-tac-toe/main.js
  intermediate-projects/DPGCode_Tic-tac-toe/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#25 Day and night Switch
  basic-projects/OussamaOsman02-DayNightSwitch/README.md
  basic-projects/OussamaOsman02-DayNightSwitch/index.html
  basic-projects/OussamaOsman02-DayNightSwitch/main.js
  basic-projects/OussamaOsman02-DayNightSwitch/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#27 📦 NEW: password generator
  basic-projects/marcelotk15-password-generator/READM.MD
  basic-projects/marcelotk15-password-generator/index.html
  basic-projects/marcelotk15-password-generator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#28 Dice Roll App Using JS
  basic-projects/imobasshir-dice/README.md
  basic-projects/imobasshir-dice/index.html
  basic-projects/imobasshir-dice/index.js
  basic-projects/imobasshir-dice/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#20 create Simon Game
  intermediate-projects/Nihal337-The Simon Game/README.md
  intermediate-projects/Nihal337-The Simon Game/game.js
  intermediate-projects/Nihal337-The Simon Game/index.html
  intermediate-projects/Nihal337-The Simon Game/sounds/blue.mp3
  intermediate-projects/Nihal337-The Simon Game/sounds/green.mp3
  intermediate-projects/Nihal337-The Simon Game/sounds/red.mp3
  intermediate-projects/Nihal337-The Simon Game/sounds/wrong.mp3
  intermediate-projects/Nihal337-The Simon Game/sounds/yellow.mp3
  intermediate-projects/Nihal337-The Simon Game/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#29 Real time weather Forcasting Application
  advance-projects/Realtime-weather-forecasting/index.html
  advance-projects/Realtime-weather-forecasting/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added the Project: Ayush-Kanduri-Advanced-Scientific-Calculator
  basic-projects/Ayush-Kanduri-Advanced-Scientific-Calculator/README.md
  basic-projects/Ayush-Kanduri-Advanced-Scientific-Calculator/index.html
  basic-projects/Ayush-Kanduri-Advanced-Scientific-Calculator/script.js
  basic-projects/Ayush-Kanduri-Advanced-Scientific-Calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#33 Added Random Quotes Generator
  advance-projects/aditi018-Random-Quotes-Generator/images/logo.png
  advance-projects/aditi018-Random-Quotes-Generator/index.html
  advance-projects/aditi018-Random-Quotes-Generator/index.js
  advance-projects/aditi018-Random-Quotes-Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added random quotes generator in intermediate projects
  .vscode/settings.json
  intermediate-projects/palaksv-RandomQuoteGenerator/README.md
  intermediate-projects/palaksv-RandomQuoteGenerator/images/logo.png
  intermediate-projects/palaksv-RandomQuoteGenerator/index.html
  intermediate-projects/palaksv-RandomQuoteGenerator/index.js
  intermediate-projects/palaksv-RandomQuoteGenerator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added Expense Tracker Project
  intermediate-projects/Abhijeet03s-Expense Tracker/README.md
  intermediate-projects/Abhijeet03s-Expense Tracker/css/style.css
  intermediate-projects/Abhijeet03s-Expense Tracker/images/Expense-Tracker.png
  intermediate-projects/Abhijeet03s-Expense Tracker/images/icons8-expense-64.png
  intermediate-projects/Abhijeet03s-Expense Tracker/index.html
  intermediate-projects/Abhijeet03s-Expense Tracker/js/app.js
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added a Project
  basic-projects/Nitesh-Mali-Tic-Tac-Toe-Game/README.md
  basic-projects/Nitesh-Mali-Tic-Tac-Toe-Game/Style.css
  basic-projects/Nitesh-Mali-Tic-Tac-Toe-Game/index.html
  basic-projects/Nitesh-Mali-Tic-Tac-Toe-Game/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#38 Random Quote Generator
  advance-projects/Baba-Yaga-1-Random-Quotes-Generator/UI.png
  advance-projects/Baba-Yaga-1-Random-Quotes-Generator/index.html
  advance-projects/Baba-Yaga-1-Random-Quotes-Generator/index.js
  advance-projects/Baba-Yaga-1-Random-Quotes-Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#43 added hover effect
  basic-projects/Tamanna-S-todo-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#44 make some changes
  basic-projects/Tamanna-S-todo-app/index.html
  basic-projects/Tamanna-S-todo-app/sky2.jpg
  basic-projects/Tamanna-S-todo-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#45 Added stopwatch project
  basic-projects/iampearlep-stopwatch/README.md
  basic-projects/iampearlep-stopwatch/index.html
  basic-projects/iampearlep-stopwatch/script.js
  basic-projects/iampearlep-stopwatch/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#46 renamed some folders to resolve conflicts
  basic-projects/clock/README.md
  basic-projects/clock/index.html
  basic-projects/clock/preview.mp4
  basic-projects/clock/script.js
  basic-projects/clock/style.css
  basic-projects/counter/README.md
  basic-projects/counter/index.html
  basic-projects/counter/preview.mp4
  basic-projects/counter/script.js
  basic-projects/counter/style.css
  basic-projects/css-vars-change-with-js/README.md
  basic-projects/css-vars-change-with-js/img.jpg
  basic-projects/css-vars-change-with-js/index.html
  basic-projects/css-vars-change-with-js/me.jpg
  basic-projects/css-vars-change-with-js/preview.mp4
  basic-projects/css-vars-change-with-js/script.js
  basic-projects/css-vars-change-with-js/style.css
  basic-projects/drumKit/README.md
  basic-projects/drumKit/background.jpg
  basic-projects/drumKit/index.html
  basic-projects/drumKit/preview.mp4
  basic-projects/drumKit/script.js
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_boom.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_clap.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_hihat.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_kick.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_openhat.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_ride.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_snare.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_tink.wav
  basic-projects/drumKit/sounds/01 - JavaScript Drum Kit_sounds_tom.wav
  basic-projects/drumKit/style.css
  basic-projects/randomColor/README.md
  basic-projects/randomColor/index.html
  basic-projects/randomColor/preview.mp4
  basic-projects/randomColor/script.js
  basic-projects/randomColor/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#51 added styling in rock-paper-scissors
  intermediate-projects/Tamanna-S-rock-paper-scissors/index.html
  intermediate-projects/Tamanna-S-rock-paper-scissors/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#57 add dicegame
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-1.png
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-2.png
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-3.png
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-4.png
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-5.png
  intermediate-projects/nithin_gith-Dicegame/Images/DIce-6.png
  intermediate-projects/nithin_gith-Dicegame/README.md
  intermediate-projects/nithin_gith-Dicegame/favicon.ico
  intermediate-projects/nithin_gith-Dicegame/index.html
  intermediate-projects/nithin_gith-Dicegame/js/myscript.js
  intermediate-projects/nithin_gith-Dicegame/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#100 Shooting Game
  intermediate-projects/leader282-ShootingGame/.gitignore
  intermediate-projects/leader282-ShootingGame/README.md
  intermediate-projects/leader282-ShootingGame/gifs/shoot.gif
  intermediate-projects/leader282-ShootingGame/images/shoot.png
  intermediate-projects/leader282-ShootingGame/index.css
  intermediate-projects/leader282-ShootingGame/index.html
  intermediate-projects/leader282-ShootingGame/index.js
  intermediate-projects/leader282-ShootingGame/sounds/collide.wav
Labels: hacktoberfest
